### ISSUE TITLE
CodeMirror as a separate repo

### ISSUE THREAD

**Issue by srid** [Atidot/reflex-widgets#1]
I'm interested in borrowing some ideas from your CodeMirror reflex widget. However I thought it would be best if I didn't have to fork it, and instead collaborated on the same project. I don't want to pull in the entire reflex-widgets repo and its deps; just codemirror. To that end, would you be open to maintaining codemirror reflex widget in its own repo?

**Comment by barakber** [comment]
Yes, I've created a repo per project.  
Usually to build and run the example under `app` you need https://github.com/Atidot/reflex-utils
